// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkemcqqidhvdkymhtjvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZW1jcXFpZGh2ZGt5bWh0anZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MzQxMTcsImV4cCI6MjA2MTMxMDExN30.zFTRIxbT3vXdu5MqeuWwian-OOqDxsw68vGSEuyJor0";

// Import the supabase client like this:
// import { supabase } from '@/integrations/supabase/client';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
